### ISSUE TITLE
No Google Cloud Platform project id

### ISSUE THREAD

**Issue by staticdev** [treethought/flask-assistant#128]
I am trying to follow the documentation and set up the project. I am not using Google Cloud, so I didn't pass the project_id as in: https://flask-assistant.readthedocs.io/en/latest/quick_start.html
 
`assist = Assistant(app, route='/route/to/webhook')`

But when I enter the bot I get the warning:

```
/app/__init__.py:31: UserWarning: 
Google Cloud Project ID is required to manage contexts using flask-assistant

                Please initialize the Assistant object with a project ID
                assist = Assistant(app, project_id='YOUR_PROJECT_ID")
```

What is the problem? Can't I use sign in without being on Google Cloud?

**Comment by treethought** [comment]
Hi @staticdev, because Dialogflow is now a part of Google Cloud, the new API uses the project ID within context names and so a project ID is required.

You don't need to actually sign into GCP or do anything from within there. After you create your agent within Dialogflow, it creates a new project for your agent to use if you do not select an existing one. You can find your agent's project ID by clicking the gear icon and viewing the "General" page.
