### ISSUE TITLE
Flask-assistant on Heroku

### ISSUE THREAD

**Issue by advak** [treethought/flask-assistant#23]
I'm building an app for google assistant which uses multiple calendars. I've set up flask-assistant, api.ai, and ngrok and tested it and everything works great. 

The next phase was deploying it to Heroku and updating the webhook inside api.ai's settings to use Heroku's webhook instead of ngrok (https://myappname.herokuapp.com/).

Heroku creates a random port rather than using 5000, so I added: 

`port = int(os.environ.get("PORT", 5000))`
`print("Starting app on port %d" % port)`
`app.run(debug=True, port=port)`

Looking on the logs I see that there is no connection between api.ai and Heroku - the webhook doesn't work.
Is there anything I need to change?
Thanks a lot for this great framework.

**Comment by treethought** [comment]
Are you sure the flask app is running correctly in heroku? 
you can test this by adding a view and checking if a standard web page works.
for example:
```
@app.route('/test_flask')
def test_page():
    return "Hello World"
```

Also, it is generally a bad idea to set debug=True for production. 

And what does your Procfile look like? I'm pretty sure you shouldn't need to specify a port.

**Comment by advak** [comment]
Thanks. removed the debugging and tested. It appears to not work. This is from the [Heroku log](https://pastebin.com/2GzkZxrs)

[This is my Procfile](https://github.com/advak/gender/blob/master/Procfile) and the rest of the project in [my repository](https://github.com/advak/gender).

**Comment by treethought** [comment]
ah, so this is a common mistake to make with the Procfile, and the heroku documentation isn't very clear. But the Procfile needs to point to the web app (Flask app) itself, rather than the file.

So try changing your procfile to: `web: webhook:app`

An additional note:
The way flask works is that it uses an internal server that you use when you run `python webhook.py`.  However, you don't want to use this for anything in production because it can only handle one request at a time.

Its pretty simple to use a proper server for production though.
Just pip install gunicorn, add it to requirments.txt. and then change the procfile above to
`web: gunicorn  webhook:app`

**Comment by advak** [comment]
Thanks! It worked

**Comment by treethought** [comment]
great to hear!
