### ISSUE TITLE
deploy and test on a Raspberry Pi

### ISSUE THREAD

**Issue by surajhes** [treethought/flask-assistant#25]
HI i have followed the guide and i am able to write a hello world action in python and i am able to test it using the Try it now option from the Api.AI Console UI. But i wanted to know how to run the same python script in a raspberry pi 3 and then wake the google home assistant and perform the same actions as i was doing here. ?

**Comment by treethought** [comment]
Running the script should be the same process as any other machine, including using ngrok to expose the port to Api.AI.

Are you trying to use your pi as a server to allow your app to respond to API, or are you trying to use your pi as an actual Google Assistant speaker/device (like google home)? Because to turn the pi into a "smart speaker" you would need to use the google assistant [sdk](https://developers.google.com/assistant/sdk/).  However I don't believe the sdk allows for most third-party apps yet, which would include flask-assistant projects.

**Comment by treethought** [comment]
Im going to close this for now as it seems to be outside the scope of this project. However, feel free to reopen if you have trouble running flask-assistant on the pi or any other questions.
