### ISSUE TITLE
Accessing the sessionId

### ISSUE THREAD

**Issue by ThaWeatherman** [treethought/flask-assistant#26]
I've dug around through the docs and haven't found a way to access things in the request JSON from api.ai such as the sessionId. How would I go about doing that? My app requires user auth, so I'll need to set the sessionId as well as read it.

**Comment by ThaWeatherman** [comment]
After digging through the code, it looks like I could Assistant.request['sessionId']. I'm guessing the info would be available in `flask.request` as well.

**Comment by ThaWeatherman** [comment]
I will need to be able to set the sessionId on the response as well, but I haven't found a way to do it yet. How would I go about setting fields in the response?

**Comment by ThaWeatherman** [comment]
Just found out that this isn't unique, so I guess I'm back to square one on auth.

**Comment by robwilkes** [comment]
I know this is closed. However I discovered it whilst searching for answers for myself.

userId can be used, it's unique and consistent across all devices on that account, it should not however be used for store important data as it can be reset.

For storing of important data (persistently) you need to link their account, and have your own OAuth setup.

https://developers.google.com/actions/identity/user-info

However, like a cookie, users can reset this identifier, so don't store important user data keyed off this identifier, because once it's reset, that information is no longer accessible by the user. The following list describes how the user ID behaves:

**Voice-activated speakers**
- When a voice matches - If a voice matches a registered voice profile on the device, a consistent user ID is returned. Each registered user has a different and consistent user ID that is associated with any conversation they have with the device.
- When no voice matches: If a registered user's voice isn't recognized by the device or no registered voice exists, then a different ID is used that is unique for just that conversation.

**Android mobile devices** - The user ID corresponds to the active Google account in the Google app and stays the same. The user ID on Android devices will also be the same as the user ID on a voice-activated speaker if all these cases are met:
- The user's Google account is the same on both devices.
- The user registered their voice on voice-activated speakers.
- The user's voice is matched on the voice-activated speaker.

**Comment by treethought** [comment]
This is really useful, thanks for sharing @robwilkes
