### ISSUE TITLE
Suggestion chips cause SSML not to render

### ISSUE THREAD

**Issue by rtgoodwin** [treethought/flask-assistant#45]
Hi, and thanks for the great work! I use Flask-Ask for the Alexa version of my skill :) 

The issue I found is this: when using Suggestion Chips, Google Assistant is rendering the `ask` as the full SSML and not processed.  I don't know if this is a limitation, but I couldn't find anything specifically about it. 

`response.py` looks like it sets the `display text` to the same text as the `speech` passed in, which also breaks `<audio>` directives I use. 

Is there a way to bypass this? I can write a way to strip out the SSML to make display text, but not sure how to override the mechanism at runtime. 

Thanks!

**Comment by rtgoodwin** [comment]
I believe this is the relevant bit in flask-ask that does this detection, if it's useful:

`def _output_speech(speech):
    try:
        xmldoc = ElementTree.fromstring(speech)
        if xmldoc.tag == 'speak':
            return {'type': 'SSML', 'ssml': speech}
    except (UnicodeEncodeError, ElementTree.ParseError) as e:
        pass
    return {'type': 'PlainText', 'text': speech}`

**Comment by treethought** [comment]
Hi @rtgoodwin, thanks for bringing this up. #40 has just been merged to address the display_text issue for ask/tell responses. So that will allow you to define the display text and speech response separately.

However, I'm unsure at the moment if that will resolve the SSML problem. The API for Actions on Google has changed since the time response.py was written and the current ssml configuration may be depreciated. 

I'll push the latest version to pip later today so you can see ifit fixes your issue. I also have a branch in the works for adapting the code to work with Actions V2 api, so a more solid solution is coming.

And isn't Flask-Ask great? I'm pretty jealous that alexa allows full audio streaming. Right now Actions/Assistant only supports SSML so the audio is capped at 90 seconds or so 🙃

**Comment by rtgoodwin** [comment]
Sounds good! Thanks for looking into it :) I'll try it out when loaded and keep an eye out for the upcoming changes.
